trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 15
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: model
        monitor: val_epoch_acc
        save_weights_only: True
        mode: max
        verbose: True
  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: /home/home/Documents/Code/cnn-image-classifier/ckpt/
model:
  num_classes: 2
  learning_rate: 0.0001
  network: RESNET50
  pretrained: true

data:
  path: /data/path
  input_size: 256
  batch_size: 1
  workers: 4
