from networks.basenetwork import BaseNetwork
from networks.efficientnetv2 import EfficientnetV2
from networks.inceptionv3network import InceptionV3
from networks.resnet50network import Resnet50
from networks.resnext50network import Resnext50
from networks.swingtransv2 import SwinTransformerV2